// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRocketLeagueRankProfile(arg1, arg2) {
  return window['go']['services']['RocketLeagueRankService']['GetRocketLeagueRankProfile'](arg1, arg2);
}
